# Generated by Django 4.2.14 on 2024-08-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('hardcover', 'Hard cover'), ('ebook', 'E-Book'), ('audiobook', 'Audiobook')], default='hardcopy', max_length=12),
        ),
    ]
